#!/usr/bin/env bash
set -eo pipefail
if [[ -n $OMNIA_DEBUG ]]; then set -x; fi

cd "$(cd "${0%/*/*}" && pwd)/lib"
source ./log.sh
verbose --list "setzer()" "$@"

export ETH_RPC_URL="$SETZER_ETH_RPC_URL"

setzer "$@"