#!/usr/bin/env bash
set -eo pipefail
if [[ -n $OMNIA_DEBUG ]]; then set -x; fi

echo >2 '{"level":"info","msg":"gofer price --config '$GOFER_CONFIG' --format ndjson '$1'"}'
gofer price --config "$GOFER_CONFIG" --format ndjson "$1" \
| jq -c '{
	asset: (.base+"/"+.quote),
	median: .price,
	sources: (
		[ ..
		| select(type == "object" and .type == "origin" and .error == null)
		| {(.base+"/"+.quote+"@"+.params.origin): (.price|tostring)}
		]
		| add
	)
}'